export const PLANS = {
  free: {
    name: 'Free',
    price: 0,
    interval: null,
    monitors: 1,
    checkInterval: 60,
    cooldown: 0,
    channels: ['email'],
    features: [
      '1 monitor, 3 locations',
      'Checked every 60 minutes',
      'Email alerts delayed 15 min',
      '7-day monitoring window',
    ],
  },
  pro: {
    name: 'Pro',
    price: 39,
    interval: null,
    monitors: 1,
    checkInterval: 5,
    cooldown: 24,
    channels: ['email', 'sms'],
    features: [
      '1 monitor, unlimited locations',
      'Checked every 5 minutes',
      'Instant email + SMS alerts',
      'Date deadline filter',
      'Smart digest alerts',
      'Advanced location insights',
      'Slot re-check alerts',
      'Monitors never expire',
      '24h cooldown on monitor changes',
    ],
  },
  multi: {
    name: 'Multi',
    price: 59,
    interval: null,
    monitors: 5,
    checkInterval: 5,
    cooldown: 0,
    channels: ['email', 'sms'],
    features: [
      'Up to 5 monitors',
      'Checked every 5 minutes',
      'Instant email + SMS alerts',
      'Date deadline filter',
      'Smart digest alerts',
      'Advanced location insights',
      'Slot re-check alerts',
      'Monitors never expire',
      'No monitor change cooldown',
    ],
  },
  express: {
    name: 'Express',
    price: 79,
    interval: null,
    monitors: 1,
    checkInterval: 1,
    cooldown: 0,
    channels: ['email', 'sms'],
    features: [
      '1 monitor, unlimited locations',
      'Checked every 1 minute',
      'Priority instant alerts',
      'Pre-verified slot confirmation',
      'All Pro features included',
      'Monitors never expire',
    ],
  },
}
