// AUTO-GENERATED by scripts/gen-product-truth.mjs from src/data/pricing.json.
// DO NOT EDIT. Change prices in src/data/pricing.json and run `npm run gen:truth`.
// Single source of truth for checkout + webhook so create-checkout (what we charge)
// and stripe-webhook (what we validate) can never drift into amount-mismatch failures.

export type PaidPlan = 'pro' | 'multi' | 'express';
export type PlanId = 'free' | PaidPlan;

export const CURRENCY = 'usd';
export const BILLING = 'one_time';
export const PAID_PLAN_IDS: PaidPlan[] = ['pro', 'multi', 'express'];

// Cents per plan, including legacy aliases accepted from historical sessions.
export const PLAN_PRICES_CENTS: Record<string, number> = {
  "pro": 3900,
  "multi": 5900,
  "express": 7900,
  "family": 5900
};

// Stripe product metadata for one-time checkout sessions (paid plans only).
export const STRIPE_PLANS: Record<PaidPlan, { priceCents: number; name: string; description: string }> = {
  "pro": {
    "priceCents": 3900,
    "name": "OnAlert Pro",
    "description": "1 monitor, SMS alerts, 5-minute checks, up to 10 locations"
  },
  "multi": {
    "priceCents": 5900,
    "name": "OnAlert Multi",
    "description": "Up to 5 monitors, SMS alerts, 5-minute checks, unlimited locations"
  },
  "express": {
    "priceCents": 7900,
    "name": "OnAlert Express",
    "description": "1-minute checks, pre-verified slots, priority alerts, unlimited locations"
  }
};

const LEGACY_ALIASES: Record<string, PaidPlan> = {
  "family": "multi"
};

/** Resolve a (possibly legacy) plan key to its canonical paid plan id. */
export function normalizePlan(plan: string): PaidPlan {
  return (LEGACY_ALIASES[plan] ?? plan) as PaidPlan;
}

/** True if `plan` is a chargeable plan key we accept (paid id or legacy alias). */
export function isValidPaidPlan(plan: string): plan is PaidPlan {
  return ["pro","multi","express","family"].includes(plan);
}
